### ISSUE TITLE
[E2E] Scenario 2.3 Service Catalog - Embedded Entity

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4321]
## Note
Before scenario make sure to execute the API call to clear the test-environment AND update call with the force flag set to true. 
### 2.3.1 Create
- Select the environment named 'test'
- Click on Show Inventory on embedded-entity-service
- Expect table to be empty
- Click on Add Instance
- Fill in the fields: 
```
    name: embedded-entity	
    service_id: 0001	
    should_fail: false
    vlan_assigment_r1:
        address: 1.2.3.5/32	
        interface_name: eth0	
        router_ip: 1.2.3.4	
        vlan_id: 2

    vlan_assigment_r2:
        address: 1.2.3.7/32	
        interface_name: eth1	
        router_ip: 1.2.3.6	
        vlan_id: 3
```
- submit form
- Expect to be redirected to Service Inventory
- Expect to find newly created instance in table
- go back to home

### 2.3.2 Diagnose
- Select the environment named 'test'
- Click on Show Inventory on embedded-entity-service
- Open created instance in table
- click diagnose button
- expect to be redirected to Diagnose Service Instance page
- expect table to be empty
- Go back to home

### 2.3.3 History
- Select the environment named 'test'
- Click on Show Inventory on embedded-entity-service
- Open created instance in table
- click history button
- expect to be redirected to Service Instance History page
- expect table to have 3 rows (states : start, creating, up)
- Go back to home

### 2.3.4 Delete instance
- Select the environment named 'test'
- Click on Show Inventory on embedded-entity-service
- Open created instance in table
- Delete instance
- Expect table to be empty
- Go back to home
